# @format

services:
  - type: web
    name: youtube-downloader
    env: node
    buildCommand: |
      npm install
      curl -L https://github.com/yt-dlp/yt-dlp/releases/latest/download/yt-dlp -o yt-dlp
      chmod +x yt-dlp
      apt-get update && apt-get install -y ffmpeg
    startCommand: node src/server/server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
