# @format

services:
  - type: web
    name: youtube-downloader
    env: node
    plan: free
    buildCommand: npm install
    startCommand: bash scripts/start-production.sh
    envVars:
      - key: NODE_ENV
        value: production
    healthCheckPath: /
    autoDeploy: true
