# @format

services:
  - type: web
    name: youtube-downloader
    env: node
    buildCommand: npm install
    startCommand: npm run start:prod
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3000
